apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.deployment.name }}
    labels:
      app: database
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
     matchLabels:
        app: database
  template:
     metadata:
       labels:
          app: database
     spec:
       containers:
       - name: {{ .Values.image.name }}
         image: {{ .Values.image.repository }}
         env:
         - name: SQLITE_DATABASE
           value: "db_filename.db"
         volumeMounts:
         - mountPath: /data
           name: sql-volume
         ports:
         - containerPort: {{ .Values.service.port }}
       volumes:
       - name: sql-volume
         hostPath:
            path: /opt/oracle

