---

apiVersion: v1
kind: Service
metadata:
   name: {{ .Values.service.name }}
spec:
   ports:
   - port: {{ .Values.service.port }}
   selector:
     app: database
   type: {{ .Values.service.type }}

